[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Frans S. Bothma fstefanusbothma@gmail.com"]
edition = "2024"

[dependencies]
actix-web = "4"
expand = "0.3.0"
reqwest = "0.12.15"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
