[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Frans S. Bothma fstefanusbothma@gmail.com"]
edition = "2024"

[dependencies]
actix-web = "4"
chrono = { version = "0.4.40", default-features = false, features = ["clock"] }
config = "0.15.11"
expand = "0.3.0"
reqwest = "0.12.15"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.16.0", features = ["v4"] }

[dependencies.sqlx]
version = "0.8.3"
default-features = false
features = [
	"runtime-tokio-rustls",
	"macros",
	"postgres",
	"uuid",
	"chrono",
	"migrate"
]
